FROM node:latest

MAINTAINER Adrián García Espinosa "age.apps.dev@gmail.com"

COPY ./app /app

WORKDIR /app

# Si no fuera una demo, lo adecuado sería hacer
# RUN npm install

EXPOSE 3000

CMD npm start
